### ISSUE TITLE
Why didn't the latest version of the jar

### ISSUE THREAD

**Issue by yann-developer** [mlaccetti/JavaPNS#17]
Why didn't the latest version of the jar？ 
http://code.google.com/p/javapns/

**Comment by mlaccetti** [comment]
Not too sure I understand what the question is.

**Comment by VincentNikkelen** [comment]
I can only guess, but maybe the other poster referred to the 2.3 beta 3 code that is available here: https://code.google.com/archive/p/javapns/source/default/commits

That code for example fixes a memory leak, as describes in the pull request (another repository):
https://github.com/fernandospr/javapns-jdk16/pull/5

Note, I just started to check if I should 'upgrade' my current 2.2 version which worked fine till now. Still investigating the situation, just started 10 minutes ago and then I found your repository. ;-)

**Comment by mlaccetti** [comment]
Hrm.  I'll take a peek and see what I can pull in.

**Comment by mlaccetti** [comment]
Added in the cherrypicked code via be42077

**Comment by mlaccetti** [comment]
Anybody feel strongly enough that I should cut a release on this, or should I just close the issue for now?

**Comment by VincentNikkelen** [comment]
I think that is completely up to you, what your intentions are with this fork.

If you have time and feel like it, I would recommend to consider doing a diff on https://code.google.com/archive/p/javapns/source/default/commits which contains other improvements.

Made a pull request (mlaccetti/JavaPNS#18) with an example of such improvement. This one is actually of interest for me.

As I am currently involved with a few other projects and recently changed employment, time is limited. I might contribute more in the future, but cannot make any promise.

Have you considered merging your fork with fernandospr/javapns-jdk16 or do you have different ambitions?

**Comment by yann-developer** [comment]
thanks
